//list of words to guess.
exports.newWord = {
  wordList:['SUPERMAN','BATMAN','WONDER WOMAN','THE FLASH','AQUAMAN','CYBORG','BATGIRL','ROBIN','NIGHTWING','BLACK CANARY','HAWKGIRL','GREEN ARROW','SUPERGIRL'],
  
};